f2fs-tool 1.7.0
commit 8b3b5f38f4041bf4ad3a7ac877c065eb02b34d01
Author: Luca Stefani <luca.stefani.ge1@gmail.com>
Date:   Sat Nov 12 11:41:22 2016 +0100

    f2fs-tools: Update to 1.7.0

    Change-Id: I33e3204bb12a0dc0bc5e1c5ba651aac66ae5d73a

commit d8690d2daa8233fcedbd92445bf72c80b5fcc818
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Thu Jul 28 13:10:46 2016 -0700

    f2fs-tools: release 1.7.0

    This version adds Host-managed SMR detection code.

    libf2fs_format_la
     - changed its body

    libf2fs_la
     - added zbc_scsi_report_zones()

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit c4f756bd80b753b385649d8c45d52edd72c3c5b3
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Fri Jul 15 10:27:23 2016 -0700

    fsck: recover symlink with zero i_size

    If we have i_blocks, we can recover i_size.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 9bbd950beb237cd2bc2df05c9b7f2a4be145f807
Author: Xue Liu <liuxueliu.liu@huawei.com>
Date:   Fri Jul 15 20:01:25 2016 +0800

    fsck.f2fs: clean up duplicated code

    Call current_nat_addr() to calculate nat block address.

    Signed-off-by: Xue Liu <liuxueliu.liu@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 0032d10a5db9eb14c4e8c605ae5f089e8df99e23
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:24 2016 +0800

    f2fs-tools: update the format of output message

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 9204a4963d065266df6028798fd41736479146eb
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:23 2016 +0800

    fsck.f2fs: free nat entry cache

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit f61616fc07ae778c16512bdb457ce79f1f4e475f
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:22 2016 +0800

    fsck.f2fs: fix typo

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit d157f4cd443b7bd5f310e97aeb86642a413939ff
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:21 2016 +0800

    fsck.f2fs: correct variable type and name

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 97b7f336729f595da2605f2155ba9742faf92e60
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:20 2016 +0800

    f2fs.fsck: fix endianess

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 86468ede9602a5cbac8f1da168a674ae8cbb2ec7
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Fri Jul 15 20:01:19 2016 +0800

    dump.f2fs: show inode->i_dir_level

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 0e60221bc35d2f331b73134df85bcad148aa89cd
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Thu Jun 16 14:39:18 2016 -0700

    mkfs: define DISCARD/SECDISCARD macro

    If SECDISCARD/DISCARD is not defined, we can set it.
    In Android, we must set -DWITH_BLKDISCARD to discard the partition.

    Change-Id: I97ca71c273877077739e58a48ead578cb9f7618e
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 9ece10f8ad0a87ca0da0514ba9f99c05cc92c2a3
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Mon Jun 13 09:36:38 2016 -0700

    mkfs/fsck: add host-managed smr feature

    This feature flag will be used by f2fs to detect HMSMR device.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit f5fa6224148fa80fc808e71f218863ce0d4b26c4
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Thu Jun 9 14:16:18 2016 -0700

    fsck.f2fs: allow zero link count for orphan inode

    This will be zeroed by f2fs during the mount time.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 6e589426157dc26ca8f77116efc9b4d3017af331
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Fri May 27 14:20:43 2016 -0700

    mkfs.f2fs: ZBC device support

    This patch adds "-m" option to configure ZBC device.

    This is to support host-managed SMR device and configure some major features
    and on-disk layout in f2fs.

    Change-Id: I383c04e6c3f4845e61910bea102f418a9b945dc0
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 8156c968aca086d6b104d6b9490c13ffd7c9ae3c
Author: Yunlei He <heyunlei@huawei.com>
Date:   Sat Jun 4 18:03:56 2016 +0800

    fsck.f2fs: modify sit dump && add nat dump

    modify sit dump && add nat dump like this:

    dump_sit:

    segment_type(0:HD, 1:WD, 2:CD, 3:HN, 4:WN, 5:CN)

    segno:      13  vblocks:512     seg_type:2      sit_pack:2

      ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff
      ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff
      ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff
      ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff  ff

    dump_nat:

    nid:    3       ino:    3       offset:    0    blkaddr:   2076417      pack:2
    nid: 1042       ino: 1042       offset:    0    blkaddr:   2087156      pack:2
    nid:57076       ino:57076       offset:    0    blkaddr:   2071232      pack:2
    nid:57118       ino:57118       offset:    0    blkaddr:   2071233      pack:2
    Signed-off-by: Yunlei He <heyunlei@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 806bfef03cf82a261397f3445e700b47bd0dfd59
Author: Yunlei He <heyunlei@huawei.com>
Date:   Wed May 18 18:00:37 2016 +0800

    fsck.f2fs: check sector size if formatted from a regular file

    This patch check sector size if formatted from a regular file,
    write the sector info to superblock from device info.

    Signed-off-by: Yunlei He <heyunlei@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit dcff6981d8a5cf419d59ef09560400ddb4f4bc00
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Tue May 3 16:58:57 2016 -0700

    fsck.f2fs: reset fsck flag if there is no bug

    Let's update checkpoint, if fsck is set without any bug.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 9a72d518f0d187bd251de501c710ebeda6cc7b33
Author: Junling Zheng <zhengjunling@huawei.com>
Date:   Tue Apr 26 10:23:32 2016 +0800

    fsck.f2fs: remove duplicated codes in sanity_check_raw_super

    Remove duplicated codes in sanity_check_raw_super().

    Signed-off-by: Junling Zheng <zhengjunling@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 7e2b796e0628fac799317f7e8d2160593e54eda2
Author: Yunlei He <heyunlei@huawei.com>
Date:   Tue Apr 26 13:25:08 2016 +0800

    resize.f2fs: replace the overprovision calculation method

    This patch replace the overprovision calculation method from
    mkfs tool.

    Signed-off-by: Yunlei He <heyunlei@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit dee113069a59093d37e5224a80172ba27e45aa95
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Wed Dec 16 16:47:23 2015 -0800

    script: add simple test script

    This patch adds a script to test sload.f2fs, defrag.f2fs, and resize.f2fs.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 2e43d6ddfa52bf1d25e262a9074913974ddf051a
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Wed Dec 9 16:18:44 2015 -0800

    sload.f2fs: support loading files into partition directly

    This patch implements loading files into the existing partition.
    For example,
     # sload.f2fs -f ./ /dev/sdb1

    Then, all the directories and files will be loaded into /dev/sdb1.
    By default, newly files should have inline_data and inline_xattr, if possible.

    Signed-off-by: Hou Pengyang <houpengyang@huawei.com>
    Signed-off-by: Liu Shuoran <liushuoran@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 53ad224fcc4e683f47c6f6c544dbd1690b394b6a
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Tue Dec 8 16:05:09 2015 -0800

    resize.f2fs: support to expand partition size

    Now user can expand existing partition with resize.f2fs.
    Currently, it doesn't support shrink an image.

    For example,
     # resize.f2fs -t [# of sectors] [image]

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit c2c2b991227eedf68e2ae66e4c3eeaa0922cfc6a
Author: Mike Frysinger <vapier@gentoo.org>
Date:   Mon Apr 18 18:19:53 2016 -0400

    fibmap: pull in sys/sysmacros.h for major/minor

    These funcs are provided by sys/sysmacros.h, so include the header
    directly.  Building with alternative C libraries can fail otherwise
    like so:

    fibmap.c: In function 'print_stat':
    fibmap.c:36:32: warning: implicit declaration of function 'major' [-Wimplicit-function-declaration]
      printf("dev       [%d:%d]\n", major(st->st_dev), minor(st->st_dev));
                                    ^
    fibmap.c:36:51: warning: implicit declaration of function 'minor' [-Wimplicit-function-declaration]
      printf("dev       [%d:%d]\n", major(st->st_dev), minor(st->st_dev));
                                                       ^
    fibmap.o: In function 'print_stat':
    tools/fibmap.c:36: undefined reference to 'minor'
    tools/fibmap.c:36: undefined reference to 'major'
    fibmap.o: In function 'stat_bdev':
    tools/fibmap.c:59: undefined reference to 'minor'
    tools/fibmap.c:59: undefined reference to 'major'

    Signed-off-by: Mike Frysinger <vapier@gentoo.org>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 01883b1e7e63fe37d231d00c270ebfcdcb686f1a
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Wed Mar 23 11:50:39 2016 -0700

    fsck.f2fs: check sanity of superblock and fix any misalignment

    This patch detects any corrupted superblock and fix misalignment when it finds,
    which is synced with the f2fs kernel module.

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 95499b1874f8c261e2110a14381858cb35bc2d65
Author: Jaegeuk Kim <jaegeuk@kernel.org>
Date:   Wed Mar 23 11:19:20 2016 -0700

    fsck.f2fs: nullify the freed ckpt pointer

    Otherwise, we get a double free error by:

    In fsck/main.c,

    545 out_err:
    546         if (sbi->ckpt)
    547                 free(sbi->ckpt);

    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit e0689005de9eca77696e1418aaf91e3a74e205df
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:59 2016 +0800

    fsck.f2fs: set fix_on if error is detected

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 72b8b87475372cdc9928986166ca299c983949b8
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:57 2016 +0800

    fsck.f2fs: check ino in nat entry and node footer

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit e0ae56cd182ac85c00209cce3792a27a919cfca9
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:55 2016 +0800

    fsck.f2fs: cache all nat entries and check each of them

    All nat entries are cached during building nat_area_bitmap, so that, in
    fsck_chk_meta, we can get and check blk_addr and ino directly, to see if
    they are in the valid range. Also, blk_addr is checked to see if the block
    is valid in sit's valid maps.

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 376c258c97b83f3b02440e4fa4313ff9e26bde64
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:54 2016 +0800

    fsck.f2fs: count the number of inodes during building nat_area_bitmap

    The nid and ino of an inode are the same. So during building
    nat_area_bitmap, we can know which nat entry represents an
    inode, thus, we can count the number of inodes.

    Then in fsck_chk_meta, the amount of inodes can be compared
    with that recorded in CP.

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

commit 2e43334233ed12bd5d1cdd3041b1c47366f9c17c
Author: Sheng Yong <shengyong1@huawei.com>
Date:   Mon Mar 14 14:16:53 2016 +0800

    fsck.f2fs: introduce -p option to check meta

    This patch introduces a new option '-p' to do more checks on NAT/SIT areas.
    '-p' has 2 levels: level 1 has the same sematics as '-a'; level 2 checks
    NAT/SIT counters to see if they matches the status in SB and CP.

    A new function, fsck_chk_meta, is called by '-p 1' to implement these
    comparsion. If errors are detected, fix_on is set, which means fsck will
    do a 'fsck -f' immediately.

    Signed-off-by: Sheng Yong <shengyong1@huawei.com>
    Signed-off-by: Jaegeuk Kim <jaegeuk@kernel.org>

Change-Id: I994ac2e348f51b879c4e47717c973a5e116aaaef